import { Link } from "react-router-dom";

export default function Navbar({ token }) {
  return (
    <nav className="space-y-2">
      <button
        className="
              w-full
              flex
              items-center
              px-4
              py-3
              rounded-2xl
              bg-[#D7BDB0]
              text-[#4B403A]
              text-sm
              font-medium
              shadow-md
            "
      >
        Dashboard
      </button>
      <Link to="/AdminDashboard/Users" state={{ token: token }}>
        <button
          className="
              w-full
              flex
              items-center
              px-4
              py-3
              rounded-2xl
              text-[#6D625B]
              text-sm
              font-medium
              hover:bg-[#F8F5F2]
              transition-all
            "
        >
          Users
        </button>
      </Link>

      <button
        className="
              w-full
              flex
              items-center
              px-4
              py-3
              rounded-2xl
              text-[#6D625B]
              text-sm
              font-medium
              hover:bg-[#F8F5F2]
              transition-all
            "
      >
        Teachers
      </button>

      <button
        className="
              w-full
              flex
              items-center
              px-4
              py-3
              rounded-2xl
              text-[#6D625B]
              text-sm
              font-medium
              hover:bg-[#F8F5F2]
              transition-all
            "
      >
        Students
      </button>

      <button
        className="
              w-full
              flex
              items-center
              px-4
              py-3
              rounded-2xl
              text-[#6D625B]
              text-sm
              font-medium
              hover:bg-[#F8F5F2]
              transition-all
            "
      >
        Classes
      </button>

      <button
        className="
              w-full
              flex
              items-center
              px-4
              py-3
              rounded-2xl
              text-[#6D625B]
              text-sm
              font-medium
              hover:bg-[#F8F5F2]
              transition-all
            "
      >
        Courses
      </button>

      <button
        className="
              w-full
              flex
              items-center
              px-4
              py-3
              rounded-2xl
              text-[#6D625B]
              text-sm
              font-medium
              hover:bg-[#F8F5F2]
              transition-all
            "
      >
        Finance
      </button>

      <button
        className="
              w-full
              flex
              items-center
              px-4
              py-3
              rounded-2xl
              text-[#6D625B]
              text-sm
              font-medium
              hover:bg-[#F8F5F2]
              transition-all
            "
      >
        Notifications
      </button>

      <button
        className="
              w-full
              flex
              items-center
              px-4
              py-3
              rounded-2xl
              text-[#6D625B]
              text-sm
              font-medium
              hover:bg-[#F8F5F2]
              transition-all
            "
      >
        Curriculum
      </button>
    </nav>
  );
}
